name: new_business_card
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter_screenutil: ^5.9.0
  flutter_pin_code_fields: ^2.2.0
  flutter_onboarding_slider: ^1.0.11
  http: ^1.1.0
  font_awesome_flutter: ^10.6.0
  azlistview: ^2.0.0
  flutter_barcode_scanner: ^2.0.0
  image_picker: ^1.0.4
  shared_value: ^3.0.0
  cached_network_image: ^3.3.0
  hexcolor: ^3.0.1

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/cards screen bottom sheet icon/
    - assets/account details icon/
    - assets/alert dialog icon/
    - assets/contacts icon/
    - assets/card_design/


